[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "chemicalrl"
version = "0.0.1"
description = "RL + fermenter sandbox"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
where = ["src"] 